### ISSUE TITLE
update FAQ

### ISSUE THREAD

**Issue by BeroBurny** [ChainSafe/sygma-validator-faucet#51]
The FAQ is outdated and should be updated to reflect the current situation!

https://validator.faucet.chainsafe.dev/faq

### Task list
- [ ]  `What is Goerli Validator Launchpad?` probably should be `Holesky`
- [ ]  `Who are we and why did we build this?` has `Goerli` but should be `Holesky`
- [ ]  `What testnets are supported?` update list to match current list :man_shrugging: 
- [ ]  `Can I withdraw my testnet eth?` :eyes: 
- [ ] Check everything in FAQ section to be sure it is current and up to date
